<a href="https://colab.research.google.com/github/ashw6/23CSBTB39-40/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
list1=[1,2,3,4,5]
list2=[5,6,7,8,9]
print(list1)
print(list2)

[1, 2, 3, 4, 5]
[5, 6, 7, 8, 9]


In [11]:
import numpy as np
a1=np.array(list1)
a2=np.array(list2)
print(a1)
print(a2)

[1 2 3 4 5]
[5 6 7 8 9]


In [19]:
list1_type=type(list1)
list2_type=type(list2)
print(list1_type)
print(list2_type)
a1_type=type(array1)
a2_type=type(array2)
print(a1_type)
print(a2_type)

<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
multiplication=a1*a2
print(multiplication)
division = a1/a2
print(division)
powerof=a1**a2
print(powerof)
addition=(a1+a2)
print("Addition of two:",addition)


[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]
[      1      64    2187   65536 1953125]
Addition of two: [ 6  8 10 12 14]


In [22]:

sin_array = np.sin(a1)


log_array = np.log(a1)


log2_array = np.log2(a1)


exp_array = np.exp(a1)

print(f"sin(array1): {sin_array}")
print(f"log(array1): {log_array}")
print(f"log2(array1): {log2_array}")
print(f"exp(array1): {exp_array}")


sin(array1): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
log(array1): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log2(array1): [0.         1.         1.5849625  2.         2.32192809]
exp(array1): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
